apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-prom-rc
  labels:
    app: nginx-ingress-prom
spec:
  replicas: 1
  selector:
    app: nginx-ingress-prom
  template:
    metadata:
      labels:
        app: nginx-ingress-prom
    spec:
      containers:
      - image: nginxdemos/nginx-ingress:1.1.0
        imagePullPolicy: Always
        name: nginx-ingress-prom
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # Uncomment the lines below to enable extensive logging and/or customization of
        # NGINX configuration with configmaps
        args:
         #- -v=3
         #- -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=$(POD_NAMESPACE)/prometheus-server-tls
